default_language_version:
  python: python3.12
fail_fast: true
files: ^adspy/.*\.py$  # must be valid Python regex
minimum_pre_commit_version: '4'  # string expected
repos:
- repo: local
  hooks:
  - id: ruff-check
    alias: lint
    name: "ruff check files.py"
    language: system  # ???
    entry: ruff check .
    verbose: true