default_language_version:
  python: python3.10
fail_fast: true
files: '^.*\.py$'  # must be a valid Python regex
minimum_pre_commit_version: '4.1.0'
repos:
- repo: local
  hooks:
  - id: check
    alias: lint
    name: "check files.py"
    language: python
    entry: make check
    verbose: true
