#[doc('list available rules')]
default:
	just --list

#[doc('build the project')]
build:
	uv build

#[doc('install the dependencies')]
sync:
	uv sync --group lint --group test

#[doc('check code')]
check:
	ruff format --check
	ruff check
	ty check

#[doc('format code')]
format:
	ruff format

#[doc('format and lint code')]
lint: format
	ruff check --fix .

#[doc('run tests')]
test:
	pytest
