[project]
name = "adspy"
version = "0.1.0"
description = "Algorithms and Data Structures in Python"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[dependency-groups]
lint = [
    "ruff>=0.9.1",
]
test = [
    "pytest>=8.3.4",
    "pytest-random-order>=1.1.1",
    "pytest-xdist>=3.6.1",
]

[tool.pytest.ini_options]
minversion = "8.3"
addopts = "-sx"
testpaths = [
    "tests",
]
verbosity_test_cases = 3

[tool.ruff]
indent-width = 4
line-length = 80
show-fixes = true
target-version = "py312"

[tool.ruff.format]
docstring-code-format = true
indent-style = "space"
line-ending = "auto"  # automatically detect the appropriate line ending.
quote-style = "double"
skip-magic-trailing-comma = false  # respect magic trailing commas.

[tool.ruff.lint]
select = [
    "B",  # flake8-bugbear
    "I",  # isort
    "Q",  # flake8-quotes
    "T",  # flake8-print-linter
    "UP",  # pyupgrade
]
fixable = ["I"]

[tool.ruff.lint.extend-per-file-ignores]
"__init__.py" = ["F401"]

[tool.ruff.lint.pydocstyle]
convention = "numpy"
