name: Python ADS CI

on:
  push:
    paths:
      - '.github/workflows/adspy.yaml'
      - 'python/adspy/**/*.py'
      - 'python/tests/**/*.py'
      - 'python/pyproject.toml'
  pull_request:
    branches:
      - main
      - 'python/*'

jobs:
  setup:
    defaults:
      run:
        working-directory: './python'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14", "pypy-3.9", "pypy-3.10"]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python {{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          allow-prereleases: true

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}

      - uses: extractions/setup-just@v3

      - name: Install the project with dependencies
        run: just sync

      - name: Build
        run: just build

      - name: Activate venv
        run: source .venv/bin/activate

      - name: Check
        run: just check

      - name: Test
        run: just test
